//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебаня_практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialsInStores = new HashSet<MaterialsInStore>();
            this.MaterialsInSupplies = new HashSet<MaterialsInSupply>();
            this.RequiredMaterials = new HashSet<RequiredMaterial>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public double DefectRate { get; set; }
        public int PartnerID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public double Cost { get; set; }
        public int MeasurementUnitID { get; set; }
        public int QuantityInPack { get; set; }
        public int MinAcceptCount { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsInStore> MaterialsInStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsInSupply> MaterialsInSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiredMaterial> RequiredMaterials { get; set; }
    }
}
