//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебаня_практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsInStore
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int MaterialID { get; set; }
        public int Amount { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Store Store { get; set; }
    }
}
