//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебаня_практика
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEntities : DbContext
    {
        public BDEntities()
            : base("name=BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AuthHistory> AuthHistories { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<MaterialsInStore> MaterialsInStores { get; set; }
        public DbSet<MaterialsInSupply> MaterialsInSupplies { get; set; }
        public DbSet<MaterialType> MaterialTypes { get; set; }
        public DbSet<MeasurementUnit> MeasurementUnits { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Partner> Partners { get; set; }
        public DbSet<PartnerType> PartnerTypes { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductsInOrder> ProductsInOrders { get; set; }
        public DbSet<ProductsInSale> ProductsInSales { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<RequiredMaterial> RequiredMaterials { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<SalePlace> SalePlaces { get; set; }
        public DbSet<SalePlaceType> SalePlaceTypes { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Supply> Supplies { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
