//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебаня_практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductsInOrders = new HashSet<ProductsInOrder>();
        }
    
        public int ID { get; set; }
        public bool Status { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Oplata { get; set; }
        public bool Proizweden { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ProductsInOrder> ProductsInOrders { get; set; }
    }
}
