//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебаня_практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductsInOrders = new HashSet<ProductsInOrder>();
            this.ProductsInSales = new HashSet<ProductsInSale>();
        }
    
        public int Article { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public double MinCostForPartner { get; set; }
        public string Logo { get; set; }
        public string Description { get; set; }
        public string PackageSize { get; set; }
        public Nullable<double> WeightWithPack { get; set; }
        public Nullable<double> WeightWithoutPack { get; set; }
        public string QualityCertificate { get; set; }
        public Nullable<int> StandardNumber { get; set; }
        public Nullable<double> Cost { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<ProductsInOrder> ProductsInOrders { get; set; }
        public virtual ICollection<ProductsInSale> ProductsInSales { get; set; }
    }
}
