//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учебаня_практика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.MaterialsInStores = new HashSet<MaterialsInStore>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MaterialsInStore> MaterialsInStores { get; set; }
    }
}
